export const SEND_EMAIL_SERVICE = "SEND-EMAIL-SERVICE";
export const SEND_SMS_SERVICE = "SEND-SMS-SERVICE";

export const USER_SERVICE = "USER-SERVICE";
export const ITEM_SERVICE = "ITEM-SERVICE";
export const INVOICE_SERVICE = "INVOICE-SERVICE";

export const MONGODB_SERVICE = "MONGO-DB-SERVICE";
export const AUDIT_SERVICE = "AUDIT-SERVICE";

export const ERROR_MIDDLEWARE = "ERROR-MIDDLEWARE";
export const MYSQL_SERVICE = "MYSQL-SERVICE";

export const UNAUTHORIZED = "UNAUTHORIZED";
export const FORBIDDEN = "FORBIDDEN";

export const SERVERLESS = "SERVERLESS";

export const API_AUTH_SERVICE = "API-AUTH-SERVICE";

export const CART_AUTH_SERVICE = "CART-AUTH-SERVICE";
export const CART_USER_SERVICE = "CART-USER-SERVICE";
export const STRIPE_SERVICE = 'STRIPE-SERVICE';