AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  # DB Proxy
  Environment:
    Description: Deploying environment
    Type: String
    AllowedValues:
      - dev
      - qa
      - stg
      - prod
    Default: dev
  CreatedBy:
    Description: Who is creating the cloudformation stack
    Type: String
    Default: CodePipeline
  ProxyIdleClientTimeout:
    Type: Number
    Default: 1800
  ProxyRequireTLS:
    Type: String
    AllowedValues:
      - true
      - false
    Default: false
  ParentVPCStack:
    Description: 'Stack name of parent VPC stack based on vpc/vpc-*azs.yaml template.'
    Type: String
  ParentRDSStack:
    Description: 'Stack name of parent RDS stack based on vpc/vpc-*azs.yaml template.'
    Type: String
  Region:
    Description: Whether we need to create the static site infrastucture
    Type: String
    AllowedValues:
      - us
      - ca
    Default: us
  IsPublic:
    Description: Whether the database is public or not
    Type: String
    Default: false
    AllowedValues: [true, false]
  # DB Proxy Target Group
  ProxyTargetConnectionBorrowTimeout:
    Type: Number
    Default: 120
  ProxyTargetMaxConnectionsPercent:
    Type: Number
    Default: 100
  ProxyTargetMaxIdleConnectionsPercent:
    Type: Number
    Default: 50
  # ProxyTargetDBClusterIdentifiers:
  #   Type: CommaDelimitedList

  # Secrets Manager
  SecretsManagerName:
    Type: String
Conditions:
  NeedPublicAccess: !Not  [!Equals [!Ref IsPublic, 'false']]
  NeedPrivateAccess: !Not  [!Equals [!Ref IsPublic, 'true']]
Resources:
  RDSProxy:
    Type: "AWS::RDS::DBProxy"
    Condition: NeedPrivateAccess
    Properties:
      Auth:
        - AuthScheme: SECRETS
          IAMAuth: DISABLED
          SecretArn: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${SecretsManagerName}"
      DBProxyName: !Join ['-', ["cart-rdx-proxy", !Ref Environment]]
      EngineFamily: MYSQL
      IdleClientTimeout: !Ref ProxyIdleClientTimeout
      RequireTLS: !Ref ProxyRequireTLS
      RoleArn: !GetAtt SecretsManagerRole.Arn
      VpcSecurityGroupIds: [{'Fn::ImportValue': !Sub '${ParentRDSStack}-SecurityGroupId'}, {'Fn::ImportValue': !Sub '${ParentVPCStack}-ClientSecurityGroup'}]
      VpcSubnetIds: !Split [',', {'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetsPrivate'}]
      Tags:
        - Key: env
          Value: !Join ['-', ["cart", !Ref Environment]]
        - Key: createdBy
          Value: !Ref CreatedBy
        - Key: application
          Value: cart-api
        - Key: userData
          Value: true
  
  RDSProxyPublic:
    Type: "AWS::RDS::DBProxy"
    Condition: NeedPublicAccess
    Properties:
      Auth:
        - AuthScheme: SECRETS
          IAMAuth: DISABLED
          SecretArn: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${SecretsManagerName}"
      DBProxyName: !Join ['-', ["cart-rdx-proxy", !Ref Environment]]
      EngineFamily: MYSQL
      IdleClientTimeout: !Ref ProxyIdleClientTimeout
      RequireTLS: !Ref ProxyRequireTLS
      RoleArn: !GetAtt SecretsManagerRole.Arn
      VpcSecurityGroupIds: [{'Fn::ImportValue': !Sub '${ParentRDSStack}-SecurityGroupId'}, {'Fn::ImportValue': !Sub '${ParentVPCStack}-ClientSecurityGroup'}]
      VpcSubnetIds: !Split [',', {'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetsPublic'}]
      Tags:
        - Key: env
          Value: !Join ['-', ["cart", !Ref Environment]]
        - Key: createdBy
          Value: !Ref CreatedBy
        - Key: application
          Value: cart-api
        - Key: userData
          Value: true

  RDSProxyTargetGroup:
    Type: "AWS::RDS::DBProxyTargetGroup"
    Properties:
      ConnectionPoolConfigurationInfo:
        ConnectionBorrowTimeout: !Ref ProxyTargetConnectionBorrowTimeout
        MaxConnectionsPercent: !Ref ProxyTargetMaxConnectionsPercent
        MaxIdleConnectionsPercent: !Ref ProxyTargetMaxIdleConnectionsPercent
      # DBClusterIdentifiers: !Ref ProxyTargetDBClusterIdentifiers
      # DBInstanceIdentifiers: [{'Fn::ImportValue': !Sub '${ParentRDSStack}-InstanceName'}]
      DBProxyName: !Ref RDSProxy
      TargetGroupName: default

  SecretsManagerRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "rds.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Description: "Use for RDS Proxy"
      ManagedPolicyArns:
        - !Ref SecretsManagerManagedPolicy
      Path: /
      RoleName: !Join ['-', ["cart-rdx-proxy-secret-role", !Ref Environment, !Ref Region]]

  SecretsManagerManagedPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      Description: "Get values from Secrets Manager"
      ManagedPolicyName: !Join ['-', ["cart-rdx-proxy-secretsmanager-policy", !Ref Environment, !Ref Region]]
      Path: /
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "secretsmanager:GetSecretValue"
              - "secretsmanager:GetResourcePolicy"
              - "secretsmanager:DescribeSecret"
              - "secretsmanager:ListSecretVersionIds"
            # Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${SecretsManagerName}"
            Resource: "*"
          - Effect: Allow
            Action:
              - "kms:Decrypt"
            # Resource: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/${SecretsManagerKMSKeyId}"
            Resource: "*"
            Condition:
              StringEquals:
                kms:ViaService: !Sub "secretsmanager.${AWS::Region}.amazonaws.com"