// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "aws-serverless-typescript-crud1",
    "version": "1"
  },
  "paths": {
    "/v1/items": {
      "get": {
        "summary": "items",
        "description": "",
        "tags": [
          "Item"
        ],
        "operationId": "items.get.v1/items",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Authorization": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "page",
            "type": "string",
            "required": true
          },
          {
            "in": "query",
            "name": "pageSize",
            "type": "string",
            "required": true
          },
          {
            "in": "query",
            "name": "filterBy",
            "type": "string",
            "required": false
          },
          {
            "in": "query",
            "name": "sortField",
            "type": "string",
            "required": false
          },
          {
            "in": "query",
            "name": "sortOrder",
            "type": "string",
            "required": false
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/GetItemsSuccess"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v1/item/{id}": {
      "get": {
        "summary": "item",
        "description": "",
        "tags": [
          "Item"
        ],
        "operationId": "item.get.v1/item/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Authorization": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/GetItemSuccess"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "put": {
        "summary": "item",
        "description": "",
        "tags": [
          "Item"
        ],
        "operationId": "item.put.v1/item/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Authorization": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateItemInputForSwagger"
            }
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/CreateItemSuccess"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "summary": "item",
        "description": "",
        "tags": [
          "Item"
        ],
        "operationId": "item.delete.v1/item/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Authorization": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Item Deleted",
            "schema": {
              "$ref": "#/definitions/DeleteItemSuccess"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v1/item": {
      "post": {
        "summary": "item",
        "description": "",
        "tags": [
          "Item"
        ],
        "operationId": "item.post.v1/item",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Authorization": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/AddItemInput"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/CreateItemSuccess"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v1/invoices": {
      "get": {
        "summary": "invoices",
        "description": "",
        "tags": [
          "Invoice"
        ],
        "operationId": "invoices.get.v1/invoices",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Authorization": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "page",
            "type": "string",
            "required": true
          },
          {
            "in": "query",
            "name": "pageSize",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/GetInvoicesSuccess"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v1/invoice/{id}": {
      "get": {
        "summary": "invoice",
        "description": "",
        "tags": [
          "Invoice"
        ],
        "operationId": "invoice.get.v1/invoice/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Authorization": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/GetInvoiceSuccess"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "put": {
        "summary": "invoice",
        "description": "",
        "tags": [
          "Invoice"
        ],
        "operationId": "invoice.put.v1/invoice/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Authorization": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateInvoiceInput"
            }
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/CreateInvoiceSuccess"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "summary": "invoice",
        "description": "",
        "tags": [
          "Invoice"
        ],
        "operationId": "invoice.delete.v1/invoice/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Authorization": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Invoice Deleted",
            "schema": {
              "$ref": "#/definitions/DeleteInvoiceSuccess"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v1/invoice": {
      "post": {
        "summary": "invoice",
        "description": "",
        "tags": [
          "Invoice"
        ],
        "operationId": "invoice.post.v1/invoice",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Authorization": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/AddInvoiceInput"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/CreateInvoiceSuccess"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v1/cartAuth/authenticateUser": {
      "post": {
        "summary": "authenticateCognitoUser",
        "description": "",
        "tags": [
          "Authentication"
        ],
        "operationId": "authenticateCognitoUser.post.v1/cartAuth/authenticateUser",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Authorization": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/AuthenticateCognitoUserInput"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/CognitoSessionTokensResponse"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v1/cartAuth/refreshUserSession": {
      "post": {
        "summary": "refreshCognitoSession",
        "description": "",
        "tags": [
          "Authentication"
        ],
        "operationId": "refreshCognitoSession.post.v1/cartAuth/refreshUserSession",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Authorization": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/RefreshCognitoSessionInput"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/CognitoSessionTokensResponse"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v1/cartAuth/resetPassword": {
      "post": {
        "summary": "resetPasswordCognito",
        "description": "",
        "tags": [
          "Authentication"
        ],
        "operationId": "resetPasswordCognito.post.v1/cartAuth/resetPassword",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Authorization": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ResetPasswordInput"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/CognitoSessionTokensResponse"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v1/cartUsers": {
      "get": {
        "summary": "cartUsers",
        "description": "",
        "tags": [
          "Cart User"
        ],
        "operationId": "cartUsers.get.v1/cartUsers",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Authorization": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "page",
            "type": "string",
            "required": true
          },
          {
            "in": "query",
            "name": "pageSize",
            "type": "string",
            "required": true
          },
          {
            "in": "query",
            "name": "filterBy",
            "type": "string",
            "required": false
          },
          {
            "in": "query",
            "name": "sortField",
            "type": "string",
            "required": false
          },
          {
            "in": "query",
            "name": "sortOrder",
            "type": "string",
            "required": false
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/GetCartUsersSuccess"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v1/cartUser": {
      "post": {
        "summary": "cartUsers",
        "description": "",
        "tags": [
          "Cart User"
        ],
        "operationId": "cartUsers.post.v1/cartUser",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Authorization": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/AddCartUserInputSwagger"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/CreateCartUserSuccess"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v1/cartUser/{cartUserId}": {
      "get": {
        "summary": "cartUserById",
        "description": "",
        "tags": [
          "Cart User"
        ],
        "operationId": "cartUserById.get.v1/cartUser/{cartUserId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Authorization": []
          }
        ],
        "parameters": [
          {
            "name": "cartUserId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/GetCartUserSuccess"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "put": {
        "summary": "cartUserById",
        "description": "",
        "tags": [
          "Cart User"
        ],
        "operationId": "cartUserById.put.v1/cartUser/{cartUserId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Authorization": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateCartUserInputSwagger"
            }
          },
          {
            "name": "cartUserId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/CreateCartUserSuccess"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "summary": "cartUserById",
        "description": "",
        "tags": [
          "Cart User"
        ],
        "operationId": "cartUserById.delete.v1/cartUser/{cartUserId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Authorization": []
          }
        ],
        "parameters": [
          {
            "name": "cartUserId",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "in": "query",
            "name": "category",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "User Deleted"
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/v1/email/{email}/cartUser": {
      "get": {
        "summary": "cartUserByEmail",
        "description": "",
        "tags": [
          "Cart User"
        ],
        "operationId": "cartUserByEmail.get.v1/email/{email}/cartUser",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Authorization": []
          }
        ],
        "parameters": [
          {
            "name": "email",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/GetCartUserSuccessful"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "properties": {
        "error": {
          "title": "Error.error",
          "type": "string"
        },
        "errorMessage": {
          "title": "Error.errorMessage",
          "type": "string"
        }
      },
      "required": [
        "error",
        "errorMessage"
      ],
      "additionalProperties": false,
      "title": "Error",
      "type": "object"
    },
    "GetItemOutput": {
      "properties": {
        "id": {
          "title": "GetItemOutput.id",
          "type": "string"
        },
        "name": {
          "title": "GetItemOutput.name",
          "type": "string"
        },
        "description": {
          "title": "GetItemOutput.description",
          "type": "string"
        },
        "price": {
          "title": "GetItemOutput.price",
          "type": "number"
        }
      },
      "required": [
        "id",
        "name",
        "price"
      ],
      "additionalProperties": false,
      "title": "GetItemOutput",
      "type": "object"
    },
    "AddItemInput": {
      "properties": {
        "name": {
          "title": "AddItemInput.name",
          "type": "string"
        },
        "description": {
          "title": "AddItemInput.description",
          "type": "string"
        },
        "price": {
          "title": "AddItemInput.price",
          "type": "number"
        }
      },
      "required": [
        "name",
        "price"
      ],
      "additionalProperties": false,
      "title": "AddItemInput",
      "type": "object"
    },
    "GetItemsSuccess": {
      "properties": {
        "data": {
          "$ref": "#/definitions/Items",
          "title": "GetItemsSuccess.data"
        }
      },
      "required": [
        "data"
      ],
      "additionalProperties": false,
      "title": "GetItemsSuccess",
      "type": "object"
    },
    "Items": {
      "properties": {
        "items": {
          "title": "Items.items",
          "type": "object"
        }
      },
      "required": [
        "items"
      ],
      "additionalProperties": false,
      "title": "Items",
      "type": "object"
    },
    "GetItemSuccess": {
      "properties": {
        "data": {
          "$ref": "#/definitions/Item",
          "title": "GetItemSuccess.data"
        }
      },
      "required": [
        "data"
      ],
      "additionalProperties": false,
      "title": "GetItemSuccess",
      "type": "object"
    },
    "CreateItemSuccess": {
      "properties": {
        "data": {
          "$ref": "#/definitions/Item",
          "title": "CreateItemSuccess.data"
        }
      },
      "required": [
        "data"
      ],
      "additionalProperties": false,
      "title": "CreateItemSuccess",
      "type": "object"
    },
    "DeleteItemSuccess": {
      "properties": {
        "data": {
          "$ref": "#/definitions/Item",
          "title": "DeleteItemSuccess.data"
        }
      },
      "required": [
        "data"
      ],
      "additionalProperties": false,
      "title": "DeleteItemSuccess",
      "type": "object"
    },
    "Item": {
      "properties": {
        "item": {
          "title": "Item.item",
          "type": "object"
        }
      },
      "required": [
        "item"
      ],
      "additionalProperties": false,
      "title": "Item",
      "type": "object"
    },
    "UpdateItemInput": {
      "properties": {
        "id": {
          "title": "UpdateItemInput.id",
          "type": "string"
        },
        "name": {
          "title": "UpdateItemInput.name",
          "type": "string"
        },
        "description": {
          "title": "UpdateItemInput.description",
          "type": "string"
        },
        "price": {
          "title": "UpdateItemInput.price",
          "type": "number"
        }
      },
      "required": [
        "id",
        "name",
        "price"
      ],
      "additionalProperties": false,
      "title": "UpdateItemInput",
      "type": "object"
    },
    "UpdateItemInputForSwagger": {
      "properties": {
        "name": {
          "title": "UpdateItemInputForSwagger.name",
          "type": "string"
        },
        "description": {
          "title": "UpdateItemInputForSwagger.description",
          "type": "string"
        },
        "price": {
          "title": "UpdateItemInputForSwagger.price",
          "type": "number"
        }
      },
      "required": [
        "name",
        "price"
      ],
      "additionalProperties": false,
      "title": "UpdateItemInputForSwagger",
      "type": "object"
    },
    "ItemFilterInput": {
      "properties": {
        "filterBy": {
          "title": "ItemFilterInput.filterBy",
          "type": "string"
        },
        "take": {
          "title": "ItemFilterInput.take",
          "type": "number"
        },
        "skip": {
          "title": "ItemFilterInput.skip",
          "type": "number"
        },
        "sortField": {
          "title": "ItemFilterInput.sortField",
          "type": "string"
        },
        "sortOrder": {
          "title": "ItemFilterInput.sortOrder"
        }
      },
      "required": [
        "take",
        "skip"
      ],
      "additionalProperties": false,
      "title": "ItemFilterInput",
      "type": "object"
    },
    "GetInvoiceOutput": {
      "properties": {
        "_id": {
          "title": "GetInvoiceOutput._id",
          "type": "string"
        },
        "items": {
          "items": [
            {},
            {},
            {}
          ],
          "additionalItems": false,
          "minItems": 3,
          "title": "GetInvoiceOutput.items",
          "type": "array"
        },
        "total": {
          "title": "GetInvoiceOutput.total",
          "type": "number"
        },
        "customerEmail": {
          "title": "GetInvoiceOutput.customerEmail",
          "type": "string"
        },
        "customerPhone": {
          "title": "GetInvoiceOutput.customerPhone",
          "type": "string"
        }
      },
      "required": [
        "_id",
        "items",
        "total",
        "customerEmail",
        "customerPhone"
      ],
      "additionalProperties": false,
      "title": "GetInvoiceOutput",
      "type": "object"
    },
    "InvoiceItem": {
      "properties": {
        "id": {
          "title": "InvoiceItem.id",
          "type": "string"
        },
        "price": {
          "title": "InvoiceItem.price",
          "type": "number"
        },
        "qty": {
          "title": "InvoiceItem.qty",
          "type": "number"
        }
      },
      "required": [
        "id",
        "price",
        "qty"
      ],
      "additionalProperties": false,
      "title": "InvoiceItem",
      "type": "object"
    },
    "AddInvoiceInput": {
      "properties": {
        "items": {
          "items": {
            "$ref": "#/definitions/InvoiceItem",
            "title": "AddInvoiceInput.items.[]"
          },
          "title": "AddInvoiceInput.items",
          "type": "array"
        },
        "total": {
          "title": "AddInvoiceInput.total",
          "type": "number"
        },
        "customerEmail": {
          "title": "AddInvoiceInput.customerEmail",
          "type": "string"
        },
        "customerPhone": {
          "title": "AddInvoiceInput.customerPhone",
          "type": "string"
        }
      },
      "required": [
        "items",
        "total",
        "customerEmail",
        "customerPhone"
      ],
      "additionalProperties": false,
      "title": "AddInvoiceInput",
      "type": "object"
    },
    "GetInvoicesSuccess": {
      "properties": {
        "data": {
          "$ref": "#/definitions/Invoices",
          "title": "GetInvoicesSuccess.data"
        }
      },
      "required": [
        "data"
      ],
      "additionalProperties": false,
      "title": "GetInvoicesSuccess",
      "type": "object"
    },
    "GetInvoiceSuccess": {
      "properties": {
        "data": {
          "$ref": "#/definitions/Invoice",
          "title": "GetInvoiceSuccess.data"
        }
      },
      "required": [
        "data"
      ],
      "additionalProperties": false,
      "title": "GetInvoiceSuccess",
      "type": "object"
    },
    "Invoices": {
      "properties": {
        "invoices": {
          "title": "Invoices.invoices",
          "type": "object"
        }
      },
      "required": [
        "invoices"
      ],
      "additionalProperties": false,
      "title": "Invoices",
      "type": "object"
    },
    "CreateInvoiceSuccess": {
      "properties": {
        "data": {
          "$ref": "#/definitions/Invoice",
          "title": "CreateInvoiceSuccess.data"
        }
      },
      "required": [
        "data"
      ],
      "additionalProperties": false,
      "title": "CreateInvoiceSuccess",
      "type": "object"
    },
    "Invoice": {
      "properties": {
        "invoice": {
          "title": "Invoice.invoice",
          "type": "object"
        }
      },
      "required": [
        "invoice"
      ],
      "additionalProperties": false,
      "title": "Invoice",
      "type": "object"
    },
    "UpdateInvoiceInput": {
      "properties": {
        "items": {
          "items": {
            "$ref": "#/definitions/InvoiceItem",
            "title": "UpdateInvoiceInput.items.[]"
          },
          "title": "UpdateInvoiceInput.items",
          "type": "array"
        },
        "total": {
          "title": "UpdateInvoiceInput.total",
          "type": "number"
        },
        "customerEmail": {
          "title": "UpdateInvoiceInput.customerEmail",
          "type": "string"
        },
        "customerPhone": {
          "title": "UpdateInvoiceInput.customerPhone",
          "type": "string"
        }
      },
      "required": [
        "items",
        "total",
        "customerEmail",
        "customerPhone"
      ],
      "additionalProperties": false,
      "title": "UpdateInvoiceInput",
      "type": "object"
    },
    "DeleteInvoiceSuccess": {
      "properties": {
        "data": {
          "$ref": "#/definitions/Invoice",
          "title": "DeleteInvoiceSuccess.data"
        }
      },
      "required": [
        "data"
      ],
      "additionalProperties": false,
      "title": "DeleteInvoiceSuccess",
      "type": "object"
    }
  },
  "securityDefinitions": {
    "Authorization": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  }
};